permissions:
  contents: write


name: déployer sur github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # si le dossier _site existe déjà dans le repo, pas besoin de lancer quarto render.
      # sinon, tu peux ajouter une étape pour vérifier la présence des fichiers.

      - name: déployer sur github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: notebooks
